export const routes = {
  SPLASH: 'SPLASH',
  HOME: 'HOME',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  PROFILE: 'PROFILE',
  SETTINGS: 'SETTINGS',
  ABOUT: 'ABOUT',
  BOTTOM_TAB: 'BOTTOM_TAB',
  HISTORY: 'HISTORY',
  PAYMENT: 'PAYMENT',
}

export const baseUrl = 'http://192.168.68.101:4000/api/'
export const pdfBaseUrl = 'http://192.168.68.101:4000/'
